services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.10-alpine
    container_name: logzilla-clickhouse
    restart: always
    env_file: ./.env
    environment:
      - CLICKHOUSE_USER=${LZ_CH_USER}
      - CLICKHOUSE_PASSWORD=${LZ_CH_PASSWORD}
      - CLICKHOUSE_DB=${LZ_CH_DB}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "${LZ_CH_HTTP_PORT}:8123"
      - "${LZ_CH_NATIVE_PORT}:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ch_data:
  ch_logs:
